site_name: Swiss Energy Forecast 
site_url: https://swissenergy.arthurgassner.ch
repo_url: https://github.com/arthurgassner/swiss-energy-frontend/
theme:
  name: material
  icon:
    logo: fontawesome/solid/plug-circle-bolt
  features:
    - content.footnote.tooltips
  palette:
    scheme: slate  # Options: default, slate, or custom
    primary: plum  # Primary color
    accent: pink     # Accent color
plugins: [] # disable search
nav:
  - Home: index.md                
  - Motivation: motivation.md                
  - Data Ingestion: data_ingestion.md                
  - EDA: eda.md
  - Modelling: modelling.md
  - Industrialization: industrialization.md
  - Deployment: deployment.md

extra_javascript:
  - https://cdn.plot.ly/plotly-latest.min.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - smarty
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format